blank_issues_enabled: false
contact_links:
  - name: Suggest a new resource
    url: https://github.com/<USER_OR_ORG>/<REPO>/issues/new?template=issue_template.md
    about: Propose an addition with a short description and link.
